FROM ubuntu:bionic
COPY dropbear-src /usr/src/dropbear
COPY build-bear.sh /etc/build-bear.sh
COPY ccache.tgz /ccache.tgz
RUN /bin/ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime || true && export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y bash build-essential git zlib1g-dev gcc ccache make autoconf libc-dev pkg-config && bash -c "time bash /etc/build-bear.sh" &&  rm -rf /usr/src/dropbear && apt-get remove -y  build-essential git zlib1g-dev gcc ccache make autoconf libc-dev pkg-config && apt-get autoremove && apt-get clean all 